auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title

title: 诗酒趁年华——my blog
url: lixinxin93.github.io
feed: /atom.xml
author_info: <a href="https://github.com/lixinxin93">lixinxin</a>
